# Generated by Django 4.0.1 on 2022-05-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_goal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['id'], 'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AlterModelOptions(
            name='boardparticipant',
            options={'ordering': ['id'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
    ]
