# Generated by Django 4.0.1 on 2022-05-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_board_options_alter_boardparticipant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AlterModelOptions(
            name='boardparticipant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
    ]
