# Generated by Django 4.0.1 on 2022-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='user_ud',
            new_name='username_tg',
        ),
        migrations.AddField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
